FROM openjdk:25-ea-17-jdk
LABEL authors="Daniel"
VOLUME /tmp
EXPOSE 8080
ADD ./target/LAB8_20212624_GTICS-0.0.1-SNAPSHOT.jar lab8_gtics_20212624.jar
ENTRYPOINT ["java","-jar","lab8_gtics_20212624.jar"]
